name: omx

services:
  motion:
    build:
      context: ..
      dockerfile: docker/Dockerfile.jazzy

    image: omx-motion:jazzy

    network_mode: host
    ipc: host
    pid: host
    privileged: true
    tty: true
    stdin_open: true

    environment:
      ROS_DOMAIN_ID: 30

    volumes:
      - /dev:/dev
      - ../open_manipulator:/root/ros2_ws/src/open_manipulator
      - ../cyclo_control:/root/ros2_ws/src/cyclo_control
      - ../robotis_interfaces:/root/ros2_ws/src/robotis_interfaces
