yolo:
  launch_arguments:
    model_type: "YOLO"
    model: "/root/ros2_ws/src/omx_ik_act_bringup/models/yolo_fruits.pt"
    tracker: "bytetrack.yaml"
    device: "cuda:0"
    fuse_model: "False"
    yolo_encoding: "bgr8"
    enable: "True"
    threshold: "0.3"
    iou: "0.7"
    imgsz_height: "480"
    imgsz_width: "640"
    half: "False"
    max_det: "300"
    augment: "False"
    agnostic_nms: "False"
    retina_masks: "False"
    input_image_topic: "/camera3/image_raw"
    image_reliability: "2"
    input_depth_topic: "/camera/depth/image_raw"
    depth_image_reliability: "1"
    input_depth_info_topic: "/camera/depth/camera_info"
    depth_info_reliability: "1"
    target_frame: "base_link"
    depth_image_units_divisor: "1000"
    namespace: "yolo"
    use_debug: "True"
    use_tracking: "True"
    use_3d: "False"
